### PR TITLE
Use s3cmd sync

### PR DESCRIPTION
**Pull request by chrisbrownie**

### CODE REVIEW

**Comment by chrisbrownie** [comment]
Sorry, was trying to create this in my own fork. Closing

**Comment by peterrus** [comment]
No problem ;) may I ask why you choose s3cmd over aws-cli?

**Comment by chrisbrownie** [comment]
I'm trying to back up a directory that only changes a small amount but is several TB (think Dropbox/Google Drive) and s3cmd sync allows me to be a lot faster and more economical about it. I've got it working [here](https://hub.docker.com/r/chrisbrownie/docker-s3-cron-backup/).

**Comment by peterrus** [comment]
I see! let me know when you consider your repo to be stable, I can place a
link to it in my readme.

**Comment by chrisbrownie** [comment]
Done! Feel free to link to it.

**Pull request closed without merging**
