### PR TITLE
Fixing target not taken into account

### PR DESCRIPTION
**Pull request by webalexeu**
Fixing #15

### CODE REVIEW

**Review by cinorid — APPROVED** [review]

**Comment by arhue** [comment]
@peterrus Can you please merge this?

Thanks.

**Comment by peterrus** [comment]
That's certainly an oversight on my part, introduced in https://github.com/peterrus/docker-s3-cron-backup/commit/ac22d48185d7eed0d92a42592844d6d6eccdc2a2

Thank you!

**Comment by peterrus** [comment]
@arhue @webalexeu a new release has been pushed: https://github.com/peterrus/docker-s3-cron-backup/releases/tag/v2.0.4

**Comment by arhue** [comment]
@peterrus That was really quick. Thank you!

**Pull request merged**
